### ISSUE TITLE
[docs] State supported Ember.js version range

### ISSUE THREAD

**Issue by mike-north** [pzuraq/ember-native-class-polyfill#11]
Looking at the README, it's not immediately clear which framework versions this polyfill supports.

Seems like at least 3.4-lts is tested
https://github.com/pzuraq/ember-native-class-polyfill/blob/cbba7e286ce95c62640786421e575391fc464432/.travis.yml#L43-L55

If this is a >= 3.4 fix, it would be a better DX to state this up front.

**Comment by mike-north** [comment]
@rwjblue that much is clear. Is the lower bound of ember.js support v3.4.0 inclusive?

**Comment by pzuraq** [comment]
Addressed this in #12, let me know if you think the copy could be clearer!
