### ISSUE TITLE
Package should support Ember 3.4.8

### ISSUE THREAD

**Issue by alexlafroscia** [pzuraq/ember-native-class-polyfill#13]
Similar issue as #8 but with the next release -- the latest `3.4.X` release is `3.4.8`, which is not supported by this package. This may troll people (like myself) who are using `ember-try` to test against `3.4.X` when the polyfill is installed.

**Comment by alexlafroscia** [comment]
Whoops! Just my luck on the timing there. Not a problem at all, I didn't realize that `3.4.8` had been released just today.

**Comment by pzuraq** [comment]
Should be fixed in v1.0.6!
