### ISSUE TITLE
Using the polyfill causes error with ember-concurrency but ember 3.6 beta does not

### ISSUE THREAD

**Issue by josemarluedke** [pzuraq/ember-native-class-polyfill#4]
Here is the reproduction: https://github.com/josemarluedke/--native-class-concurrency

When using this polyfill with ember-concurrency, it produces the error below, but if I run the same code with Ember `v3.6.0-beta.4`, it does not error out.

```Class constructor ComputedProperty cannot be invoked without 'new'```

My understanding is that we should avoid calling new on ember objects, which ember-concurrency does, so the error from the polyfill seem to be right, but I don't get why running in Ember wound not cause the error.

https://github.com/machty/ember-concurrency/blob/master/addon/index.js#L54

**Comment by rwjblue** [comment]
This issue is here:

https://github.com/machty/ember-concurrency/blob/af891b292428ad4a789c1e172a1293119d42f4d9/addon/-task-property.js#L418

It should probably be rewritten as `class TaskProperty extends ComputedProperty{}`...

**Comment by buschtoens** [comment]
Tracked and fixed upstream in https://github.com/machty/ember-concurrency/issues/261. 🚀
