### ISSUE TITLE
Package should support Ember 3.4.7

### ISSUE THREAD

**Issue by alexlafroscia** [pzuraq/ember-native-class-polyfill#8]
It seems like `ember-source@3.4.7` was released shortly after the most recent version of this add-on. For any users choosing to bump to `3.4.7` instead of `3.5` or later (probably not many) or Ember Add-on authors that are testing against a generic `3.4` version (probably many), this package should support `3.4.7`.

**Comment by rwjblue** [comment]
Yep, definitely agree.

**Comment by alexlafroscia** [comment]
I wanted to take care of fixing this myself, but I'm not sure where the `vendor/ember-native-class-polyfill/*.*.*/` files are generated.

If someone can let me know where that comes from (and presumably, how they are doctored) I'm happy to make the PR to close this issue.

**Comment by alexlafroscia** [comment]
Note: I think the lack of support here also explains why the tests are failing, since the `3.4.0` scenario in Ember Try is running against the unsupported `3.4.7`

**Comment by pzuraq** [comment]
The polyfill branches are

* 3.4 https://github.com/emberjs/ember.js/pull/17167
* 3.5 https://github.com/emberjs/ember.js/pull/17168

It should be possible to rebase the current branch ontop of the latest patch release and rebuild. For the _non_ legacy part of the polyfill, you have to remove all of the ES5 transforms. I can do this later today, but happy to merge if you have time.

**Comment by alexlafroscia** [comment]
I probably won't have time, to be honest. I have a bunch of work stuff on my plate for today.

**Comment by pzuraq** [comment]
Support for 3.4.7 added in v1.0.5!
